In [16]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('data/features.csv', index_col='match_id')

In [17]:
df.head(15)

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,r2_hero,r2_level,r2_xp,r2_gold,r2_lh,r2_kills,r2_deaths,r2_items,r3_hero,r3_level,r3_xp,r3_gold,r3_lh,r3_kills,r3_deaths,r3_items,r4_hero,r4_level,r4_xp,r4_gold,r4_lh,r4_kills,r4_deaths,r4_items,r5_hero,r5_level,r5_xp,r5_gold,r5_lh,r5_kills,r5_deaths,r5_items,d1_hero,d1_level,d1_xp,d1_gold,d1_lh,d1_kills,d1_deaths,d1_items,d2_hero,d2_level,d2_xp,d2_gold,d2_lh,d2_kills,d2_deaths,d2_items,d3_hero,d3_level,d3_xp,d3_gold,d3_lh,d3_kills,d3_deaths,d3_items,d4_hero,d4_level,d4_xp,d4_gold,d4_lh,d4_kills,d4_deaths,d4_items,d5_hero,d5_level,d5_xp,d5_gold,d5_lh,d5_kills,d5_deaths,d5_items,first_blood_time,first_blood_team,first_blood_player1,first_blood_player2,radiant_bottle_time,radiant_courier_time,radiant_flying_courier_time,radiant_tpscroll_count,radiant_boots_count,radiant_ward_observer_count,radiant_ward_sentry_count,radiant_first_ward_time,dire_bottle_time,dire_courier_time,dire_flying_courier_time,dire_tpscroll_count,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time,duration,radiant_win,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire
match_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,1430198770,7,11,5,2098,1489,20,0,0,7,67,3,842,991,10,0,0,4,29,5,1909,1143,10,0,0,8,20,3,757,741,6,0,0,7,105,3,732,658,4,0,1,11,4,3,1058,996,12,0,0,6,42,4,1085,986,12,0,0,4,21,5,2052,1536,23,0,0,6,37,3,742,500,2,0,0,8,84,3,958,1003,3,1,0,9,7.0,1.0,9.0,NaN,134.0,-80.0,244.0,2,2,2,0,35.0,103.0,-84.0,221.0,3,4,2,2,-52.0,2874,1,1796,0,51,0
1,1430220345,0,42,4,1188,1033,9,0,1,12,49,4,1596,993,10,0,1,7,67,4,1506,1502,18,1,0,7,37,3,669,631,7,0,0,7,26,2,415,539,1,0,0,5,39,5,1960,1384,16,0,0,8,88,3,640,566,1,0,1,5,79,3,720,1350,2,2,0,12,7,2,440,583,0,0,0,7,12,4,1470,1622,24,0,0,9,54.0,1.0,7.0,NaN,173.0,-80.0,NaN,2,0,2,0,-20.0,149.0,-84.0,195.0,5,4,3,1,-5.0,2463,1,1974,0,63,1
2,1430227081,7,33,4,1319,1270,22,0,0,12,98,3,1314,775,6,0,0,6,20,3,1297,909,0,1,0,6,27,5,2360,2096,26,1,1,6,4,3,1395,1627,27,0,0,9,22,5,2305,2028,19,1,1,10,66,3,1024,959,19,0,1,10,86,3,755,620,3,0,0,8,29,4,1319,667,4,0,0,7,80,3,1350,1512,25,0,0,7,224.0,0.0,3.0,NaN,63.0,-82.0,NaN,2,5,2,1,-39.0,45.0,-77.0,221.0,3,4,3,1,13.0,2130,0,0,1830,0,63
3,1430263531,1,29,4,1779,1056,14,0,0,5,30,2,539,539,1,0,0,6,75,5,2037,1139,15,0,0,6,37,2,591,499,0,0,0,6,41,3,712,1075,12,0,0,6,96,5,1878,1174,17,0,0,6,48,3,732,1468,22,0,0,10,15,4,1681,1051,11,0,0,7,102,2,674,537,1,0,0,7,20,2,510,499,0,0,0,7,NaN,NaN,NaN,NaN,208.0,-75.0,NaN,0,3,2,0,-30.0,124.0,-80.0,184.0,0,4,2,0,27.0,1459,0,1920,2047,50,63
4,1430282290,7,13,4,1431,1090,8,1,0,8,27,2,629,552,0,0,1,7,30,3,884,927,0,1,0,8,72,3,925,1439,16,1,0,11,93,4,1482,880,7,0,0,8,26,3,704,586,1,0,2,9,69,3,1169,1665,20,1,0,7,22,3,1055,638,1,0,0,9,25,5,1815,1275,18,0,0,8,8,4,1119,904,6,0,1,7,-21.0,1.0,6.0,NaN,166.0,-81.0,181.0,1,4,2,0,46.0,182.0,-80.0,225.0,6,3,3,0,-16.0,2449,0,4,1974,3,63
5,1430284186,1,11,5,1961,1461,19,0,1,6,20,2,441,686,4,0,0,5,28,4,1874,1438,22,0,0,4,25,2,528,800,1,1,0,9,65,3,799,785,6,0,1,6,55,3,847,785,7,0,1,7,52,2,455,967,2,1,0,11,3,2,279,916,0,1,0,10,73,5,2065,2565,26,0,0,13,48,5,2029,1781,29,0,0,8,78.0,1.0,7.0,NaN,35.0,-85.0,182.0,5,4,2,1,-27.0,2.0,-86.0,212.0,4,4,4,0,-43.0,1453,0,512,2038,0,63
8,1430293701,1,8,3,967,1136,7,1,0,8,57,4,1774,1592,19,1,0,8,7,3,904,1119,7,0,1,12,21,4,1523,1061,5,1,1,8,36,2,553,657,1,0,2,10,22,4,1958,1680,19,1,1,9,30,3,1026,704,0,0,1,8,72,3,1161,1668,19,1,0,9,101,3,681,931,6,1,1,13,47,5,2282,1998,30,1,0,16,-34.0,1.0,7.0,NaN,229.0,-77.0,299.0,11,3,3,2,-35.0,6.0,-86.0,182.0,3,6,3,0,10.0,1968,0,1536,1983,12,63
9,1430299335,7,35,5,2117,1252,16,0,0,6,15,3,1378,1430,23,0,0,4,83,2,259,500,0,0,0,6,29,3,825,818,8,0,0,8,101,2,357,500,0,0,0,7,100,2,350,523,0,0,0,9,25,5,2323,1890,25,0,0,7,26,2,310,523,0,0,0,7,44,4,1387,1275,19,0,0,7,96,4,1408,883,8,0,0,7,NaN,NaN,NaN,NaN,NaN,-85.0,NaN,1,2,2,1,26.0,119.0,-61.0,NaN,2,3,4,0,-15.0,4079,1,1540,0,63,0
11,1430308974,1,17,5,1527,906,10,0,1,7,91,3,733,499,0,0,0,4,53,4,1571,1257,8,1,0,8,72,3,939,1229,18,0,0,4,30,1,310,549,1,0,1,7,90,3,836,790,0,1,0,9,96,3,1046,925,10,0,0,9,35,5,2088,1732,18,1,0,10,19,4,1290,946,11,0,1,5,7,3,952,750,4,0,0,5,-18.0,1.0,5.0,NaN,77.0,-81.0,180.0,4,1,2,1,9.0,NaN,-84.0,226.0,1,3,4,0,26.0,3071,0,0,1572,0,63
12,1430316105,7,15,5,1651,1060,14,0,1,10,41,3,951,1378,19,0,0,6,74,4,1563,855,8,0,1,4,90,3,758,499,0,0,0,7,42,3,708,613,4,0,0,10,76,5,2507,1653,17,1,0,9,20,3,723,748,0,0,0,11,83,3,767,850,0,1,0,7,99,3,1336,989,12,0,0,6,52,3,846,1314,20,0,0,6,42.0,1.0,7.0,NaN,NaN,-79.0,NaN,2,3,2,0,-24.0,186.0,-83.0,195.0,1,3,2,0,16.0,2384,0,0,2038,0,63
14,1430325079,1,22,5,1988,1804,21,1,0,6,25,2,537,630,3,0,0,11,1,4,1638,1965,34,0,0,9,96,4,1749,901,9,0,0,6,79,2,511,655,5,0,0,6,98,3,1170,664,4,0,0,4,13,4,1669,1088,13,0,0,6,37,2,619,550,1,0,1,8,94,2,765,1206,17,0,0,6,27,3,755,542,1,0,0,9,-8.0,0.0,0.0,NaN,15.0,-74.0,203.0,1,6,4,0,-27.0,166.0,-83.0,NaN,1,2,2,1,34.0,912,1,2047,1974,63,63
15,1430330210,7,27,3,819,763,12,0,2,9,52,2,488,697,9,0,2,9,82,5,2095,1602,25,1,2,4,60,3,902,868,5,0,1,6,112,2,547,615,2,0,0,8,39,5,2205,1515,12,1,0,5,31,3,1027,1151,1,1,0,9,85,3,885,1305,5,1,0,7,61,5,2777,2787,28,3,0,5,70,3,1145,1443,13,0,0,5,31.0,1.0,7.0,NaN,45.0,-44.0,NaN,6,4,3,3,-19.0,86.0,-71.0,229.0,0,4,2,0,142.0,1001,0,0,2047,0,63
17,1430331421,1,68,2,611,500,0,0,0,6,99,2,392,545,1,0,0,7,44,3,1015,1800,25,0,0,5,39,5,2038,1840,24,1,0,6,26,2,527,600,0,0,0,8,30,2,500,500,0,0,0,7,36,4,1650,736,6,0,1,4,67,4,1470,1599,28,0,0,8,96,4,1175,615,3,0,0,6,102,2,627,753,4,0,0,9,5.0,0.0,3.0,NaN,58.0,-84.0,223.0,0,3,2,0,14.0,NaN,-86.0,180.0,0,5,2,0,-43.0,3270,1,1956,0,63,0
20,1430341277,1,26,3,739,585,4,0,0,11,39,5,2448,2146,19,2,0,12,48,4,1350,1695,29,0,0,13,7,2,648,801,3,0,0,10,51,3,949,653,4,0,1,9,83,2,359,616,0,0,0,8,2,3,1235,1887,30,1,0,8,25,3,730,663,2,0,0,13,11,5,1818,1231,15,0,2,9,61,4,1655,965,13,0,0,7,102.0,0.0,1.0,NaN,107.0,-85.0,210.0,3,1,2,2,20.0,245.0,-83.0,182.0,4,3,4,3,22.0,1584,1,1974,1542,63,15
21,1430342692,1,29,2,430,642,1,0,1,5,50,2,668,595,4,0,2,10,12,4,1277,1773,27,0,1,17,26,2,436,546,1,0,0,7,22,4,1156,995,11,0,3,6,20,2,593,1086,0,1,0,7,25,6,2852,2465,20,3,0,11,68,2,623,642,0,0,0,7,72,3,1407,2259,32,2,0,8,96,4,1679,1360,11,1,0,10,-17.0,1.0,8.0,NaN,57.0,-86.0,NaN,7,4,2,1,-5.0,100.0,-85.0,205.0,2,4,1,0,19.0,1957,0,1796,1983,55,63

In [4]:
df.describe()

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,...,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time,duration,radiant_win,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire
count,9.723000e+04,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000,...,97230.000000,97230.000000,97230.000000,95404.000000,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000,97230.000000
mean,1.444232e+09,2.630999,51.517104,3.442672,1233.405801,1147.899702,11.231996,0.357009,0.362285,8.271315,...,3.349553,2.448339,0.689119,-6.901922,2332.247886,0.518503,1309.227790,1286.310820,40.599095,41.337036
std,5.515393e+06,2.835761,32.564211,1.111741,566.588895,464.111662,9.041620,0.663889,0.626704,2.497575,...,1.155609,0.813459,0.710122,40.701397,715.806850,0.499660,853.921365,851.009148,27.871645,27.064873
min,1.430199e+09,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-84.000000,900.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.440815e+09,1.000000,22.000000,3.000000,767.000000,746.000000,2.000000,0.000000,0.000000,7.000000,...,3.000000,2.000000,0.000000,-31.000000,1818.000000,0.000000,36.000000,256.000000,3.000000,3.000000
50%,1.446338e+09,1.000000,50.000000,3.000000,1175.000000,1113.000000,11.000000,0.000000,0.000000,8.000000,...,3.000000,2.000000,1.000000,-16.000000,2268.000000,1.000000,1824.000000,1798.000000,63.000000,60.000000
75%,1.448829e+09,7.000000,75.000000,4.000000,1704.000000,1479.000000,19.000000,1.000000,1.000000,10.000000,...,4.000000,3.000000,1.000000,8.000000,2778.000000,1.000000,1974.000000,1974.000000,63.000000,63.000000
max,1.450313e+09,7.000000,112.000000,6.000000,3319.000000,4332.000000,47.000000,8.000000,5.000000,34.000000,...,9.000000,9.000000,13.000000,300.000000,8452.000000,1.000000,2047.000000,2047.000000,63.000000,63.000000

#### Описание признаков в таблице

- `match_id`: идентификатор матча в наборе данных
- `start_time`: время начала матча (unixtime)
- `lobby_type`: тип комнаты, в которой собираются игроки (расшифровка в `dictionaries/lobbies.csv`)
- Наборы признаков для каждого игрока (игроки команды Radiant — префикс `rN`, Dire — `dN`):
    - `r1_hero`: герой игрока (расшифровка в dictionaries/heroes.csv)
    - `r1_level`: максимальный достигнутый уровень героя (за первые 5 игровых минут)
    - `r1_xp`: максимальный полученный опыт
    - `r1_gold`: достигнутая ценность героя
    - `r1_lh`: число убитых юнитов
    - `r1_kills`: число убитых игроков
    - `r1_deaths`: число смертей героя
    - `r1_items`: число купленных предметов
- Признаки события "первая кровь" (first blood). Если событие "первая кровь" не успело произойти за первые 5 минут, то признаки принимают пропущенное значение
    - `first_blood_time`: игровое время первой крови
    - `first_blood_team`: команда, совершившая первую кровь (0 — Radiant, 1 — Dire)
    - `first_blood_player1`: игрок, причастный к событию
    - `first_blood_player2`: второй игрок, причастный к событию
- Признаки для каждой команды (префиксы `radiant_` и `dire_`)
    - `radiant_bottle_time`: время первого приобретения командой предмета "bottle"
    - `radiant_courier_time`: время приобретения предмета "courier" 
    - `radiant_flying_courier_time`: время приобретения предмета "flying_courier" 
    - `radiant_tpscroll_count`: число предметов "tpscroll" за первые 5 минут
    - `radiant_boots_count`: число предметов "boots"
    - `radiant_ward_observer_count`: число предметов "ward_observer"
    - `radiant_ward_sentry_count`: число предметов "ward_sentry"
    - `radiant_first_ward_time`: время установки командой первого "наблюдателя", т.е. предмета, который позволяет видеть часть игрового поля
- Итог матча (данные поля отсутствуют в тестовой выборке, поскольку содержат информацию, выходящую за пределы первых 5 минут матча)
    - `duration`: длительность
    - `radiant_win`: 1, если победила команда Radiant, 0 — иначе
    - Состояние башен и барраков к концу матча (см. описание полей набора данных)
        - `tower_status_radiant`
        - `tower_status_dire`
        - `barracks_status_radiant`
        - `barracks_status_dire`

### Пропуски в данных

In [14]:
total_rows = len(df)
counts = df.describe().loc['count', :]
counts_na = counts[counts < total_rows]
counts_na.apply(lambda x: (total_rows - x)/total_rows).sort_values(ascending=False)

first_blood_player2            0.452402
radiant_flying_courier_time    0.282619
dire_flying_courier_time       0.268415
first_blood_player1            0.201100
first_blood_team               0.201100
first_blood_time               0.201100
dire_bottle_time               0.166029
radiant_bottle_time            0.161380
radiant_first_ward_time        0.018883
dire_first_ward_time           0.018780
radiant_courier_time           0.007117
dire_courier_time              0.006953
Name: count, dtype: float64

### Обоснование пропусков

- `first_blood_player2`(второй игрок, причастный к событию): первое убийство совершается одним игроком в 45% случаев
- `radiant_flying_courier_time`(время приобретения предмета "flying_courier"): данный предмет игроки могут не приобретать в первые минут игры (28%)
- `dire_flying_courier_time`: аналогично radiant_flying_courier_time, доля пропусков примерно одинаковая
- `first_blood_player1`(игрок, причастный к событию): в первые 5 минут может и не быть убийств
- `first_blood_team`(команда, совершившая первую кровь (0 — Radiant, 1 — Dire): аналогично first_blood_player1, доля пропусков совпадает
- `first_blood_time`(игровое время первой крови): аналогично first_blood_player1, доля пропусков совпадает
- `dire_bottle_time`(время первого приобретения командой предмета "bottle"): данный предмет игроки могут не приобретать в первые минут игры (16%)
- `radiant_bottle_time`: аналогично dire_bottle_time

- `radiant_first_ward_time`(время установки командой первого "наблюдателя", т.е. предмета, который позволяет видеть часть игрового поля): редкое явление (1%), команда почти не ставит "наблюдателя" в первые 5 минут игры
- `dire_first_ward_time`: аналогично radiant_first_ward_time
- `radiant_courier_time`(время приобретения предмета "courier"): редкое явление (0.7%), команда не приобретает предмет "courier" в первые 5 минут игры
- `dire_courier_time`: аналогчино radiant_courier_time

### Целевая переменная

In [18]:
df['radiant_win'].value_counts(normalize=True)

1    0.518503
0    0.481497
Name: radiant_win, dtype: float64